In [1]:
import pandas as pd

df_2005 = pd.read_excel("C:/Users/hp/working-with-data/research-project/data/oringinal/05-table-43a.xls", skiprows=5)
df_2010 = pd.read_excel("C:/Users/hp/working-with-data/research-project/data/oringinal/10-table-43a.xls", skiprows=5)
df_2015 = pd.read_excel("C:/Users/hp/working-with-data/research-project/data/oringinal/15-table-43a.xls", skiprows=6)
df_2019 = pd.read_excel("C:/Users/hp/working-with-data/research-project/data/oringinal/19-table-43a.xls", skiprows=6)

def standardize_race_cols(df, year):
    black_col  = [c for c in df.columns if "black" in c.lower()][0]
    native_col = [c for c in df.columns if "indian" in c.lower()][0]
    if year == 2010 or 2005:
        pi_col = [c for c in df.columns if "pacific" in c.lower() and "1" not in c][0]
        df["Asian_PI"] = df[pi_col]
    else:
        asian_col = [c for c in df.columns if c.lower().startswith("asian") and "1" not in c][0]
        pi_col    = [c for c in df.columns if "pacific" in c.lower() and "1" not in c][0]
        df["Asian_PI"] = df[asian_col] + df[pi_col]
    df.rename(columns={black_col: "Black", native_col: "Native"}, inplace=True)
    return df

df_2005 = standardize_race_cols(df_2005, 2005)
df_2010 = standardize_race_cols(df_2010, 2010)
df_2015 = standardize_race_cols(df_2015, 2015)
df_2019 = standardize_race_cols(df_2019, 2019)

In [2]:
def find_off_col(df):
    return [c for c in df.columns if "off" in c.lower()][0]

off_2005 = find_off_col(df_2005)
off_2010 = find_off_col(df_2010)
off_2015 = find_off_col(df_2015)
off_2019 = find_off_col(df_2019)

keep = ["Year","Total","White","Black","Native","Asian_PI"]
rows = []
for df, off_col, year in [
    (df_2005, off_2005, 2005),
    (df_2010, off_2010, 2010),
    (df_2015, off_2015, 2015),
    (df_2019, off_2019, 2019),
]:
    r = df[df[off_col].str.contains("drug abuse", case=False, na=False)].copy()
    r["Year"] = year
    rows.append(r[keep])

df_drug = pd.concat(rows, ignore_index=True)

df_drug

   Year      Total     White     Black   Native  Asian_PI
0  2005  1330802.0  861645.0  451375.0   8600.0    9182.0
1  2010  1270443.0  846736.0  404609.0   8766.0   10332.0
2  2015  1136950.0  803809.0  307140.0  11717.0    1848.0
3  2019  1052101.0  748874.0  274670.0  14098.0    2602.0

In [3]:
df_drug.to_csv("C:/Users/hp/working-with-data/research-project/data/processed/cleaned_table43_drug_abuse.csv", index=False)